version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: expenseTrackerDB
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - my-network


  app:
    image: tahsin/expense-tracker:v1
    container_name: expense_tracker_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/expenseTrackerDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - my-network


volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
